apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami-helm
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://cowboysysop.github.io/charts/
      chart: whoami
      targetRevision: 5.3.0
      helm:
        valueFiles:
          - $values/apps/whoami-helm/values.yaml

    - repoURL: https://github.com/iessenov/gitops.git
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: whoami-helm

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true