apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-app
  namespace: nginx-app
spec:
  ingressClassName: ingress-nginx-apps
  rules:
  - host: www.essenov.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-app
            port:
              number: 80