apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-content-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
  - ReadOnlyMany
  local:
    path: /home/essenov/web-content  # Change this to your local drive path
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nginx-app
          operator: In
          values:
          - "true"  
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-content-pvc
  namespace: nginx-app
spec:
  storageClassName: local-path
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nginx-content-pv
