apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syncthing
  namespace: argocd
  annotations:
    cache-bust: "3"
spec:
  project: default

  source:
    repoURL: https://github.com/iessenov/gitops.git
    targetRevision: main
    path: apps/syncthing
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: syncthing

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
