apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config
  namespace: qbittorrent
data:
  QBT_LEGAL_NOTICE: "confirm"
  QBT_VERSION: "latest"
  QBT_WEBUI_PORT: "8080"
  QBT_TORRENTING_PORT: "6881"
  TZ: "Europe/Sofia"
  UMASK: "002"
