apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-webui
  namespace: qbittorrent
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: webui
  selector:
    app: qbittorrent
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-torrenting
  namespace: qbittorrent
spec:
  type: ClusterIP
  ports:
    - port: 6881
      targetPort: 6881
      protocol: TCP
      name: torrenting-tcp
    - port: 6881
      targetPort: 6881
      protocol: UDP
      name: torrenting-udp
  selector:
    app: qbittorrent
